### DISCUSSION TITLE
Accessing parquet files from Planetary Computer Docker image

### DISCUSSION THREAD

**Discussion by glaroc** [microsoft/PlanetaryComputer#41] [Q&A]
Hi, I'm trying to access GBIF data locally using Dask from the Planetary Computer Docker image. If I run the code on the Jupyter Hub on the PC, it works. However, running the same code within the Docker gives me an error: 

````python

import pystac_client
from dask_gateway import GatewayCluster
import planetary_computer
import dask.dataframe as dd
from dotenv import load_dotenv
import os

load_dotenv() 
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
)

cluster = GatewayCluster(
 "https://pccompute.westeurope.cloudapp.azure.com/compute/services/dask-gateway",
 proxy_address="gateway://pccompute-dask.westeurope.cloudapp.azure.com:80",
 auth="jupyterhub",
 image="mcr.microsoft.com/planetary-computer/python:latest"
)
cluster.scale(20)
client = cluster.get_client()

search = catalog.search(collections=["gbif"])
items = search.get_all_items()
items = {x.id: x for x in items}
item = list(items.values())[0]

signed_asset = planetary_computer.sign(item).assets["data"]
#signed_asset.extra_fields["table:storage_options"]

filters=[('species', '==', 'Acer saccharum'), ('decimallatitude', '<', 62.3), ('decimallatitude', '>', 45.2), ('decimallongitude', '>', -77.3), ('decimallongitude', '<', -60.3)]

df = dd.read_parquet(
    signed_asset.href,
    storage_options=signed_asset.extra_fields["table:storage_options"],
    filters=filters,
    dataset={"require_extension": None},
    engine="pyarrow"
)

res=df.compute()

````
This gives me: 
````
TypeError: dataset() got an unexpected keyword argument 'require_extension'
````

The variable JUPYTERHUB_API_TOKEN is set properly and the Dask versions seem to the same within the Docker and on the Hub.  Is there something different we should do to run this from the Docker image ?

**Comment by TomAugspurger** [comment]
Can you check what version of Dask you're using locally? That was added somewhere in the 2021.11 or 2021.12 range IIRC. See https://github.com/dask/dask/issues/8491.

Edit: Oh, sorry, I should have read more closely. You say you're using the docker image. Can you share your `docker run` and the version of the image you're using?

**Reply by glaroc** [reply]
I'm setting the environment variables with docker-compose. Here is the Dockerfile. 
````
FROM mcr.microsoft.com/planetary-computer/python:latest
SHELL ["conda", "run", "-n", "notebook", "/bin/bash", "-c"]
RUN pip3 install appdirs geojson_rewind geomet requests_cache matplotlib python-dotenv

# The code to run when container is started:
RUN python
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "notebook"]
````

compose.yml
````
version: '2.3'
services:
  pc-dock:
    build: .
    image: "planetary-computer-pygbif"
    user: root
    command:
      - python
    volumes:
      - ${HOST_PATH}/scripts/:/home/jovyan/scripts/
      - ${HOST_PATH}/output:/output/:rw
    environment:
      - GRANT_SUDO=yes
      - JUPYTERHUB_API_TOKEN=${JUPYTERHUB_API_TOKEN}
      - DASK_GATEWAY__AUTH__TYPE="jupyterhub"
      - DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE="mcr.microsoft.com/planetary-computer/python:latest"
      - DASK_GATEWAY__ADDRESS="https://pccompute.westeurope.cloudapp.azure.com/compute/services/dask-gateway"
      - DASK_GATEWAY__PROXY_ADDRESS="gateway://pccompute-dask.westeurope.cloudapp.azure.com:80"
    ports:
      - "8888:8888"
````

And then I just do. 
````
docker-compose run pc-dock python
````
